### ISSUE TITLE
Out of bounds for Stackage

### ISSUE THREAD

**Issue by jsantos17** [stackbuilders/twitter-feed#43]
The library isn't working with the last Aeson version in stackage. Please refer to https://github.com/fpco/stackage/issues/2177 for more details. We need to fix the bounds of the Aeson dependency. Ideally, we want this library to work with as many versions of Aeson as possible. Please check on what we depend and and how we can make the bounds broader. Ping me if you have questions :)

**Comment by mrkkrp** [comment]
@jmorocho Heads up, chances are you won't need to do anything but changing `1.1` to `1.2` in the cabal file, since there are no breaking changes in version 1.1. If this is the case, you can just edit package information on Hackage without uploading dummy package with only dependency boundaries changed.

To edit package information go here: https://hackage.haskell.org/package/twitter-feed, and click the “edit package information” link. Then select the latest version you want to edit and update the Cabal file, then click “publish new revision” (or “version”, I don't remember working exactly).

**Comment by jmorocho** [comment]
@jsantos17 `stack.yaml` and `twitter-feed.cabal` files updated solving issue with Aeson package.

**Comment by mrkkrp** [comment]
Please comment here: https://github.com/fpco/stackage/issues/2177 to let them know that the package is good to go now.
